### ISSUE TITLE
Unknown module mentioned in Drupal forms

### ISSUE THREAD

**Issue by ivangrozni** [drunomics/lupus-decoupled-website#78]
Drupal forms advanced topic refers to _Nuxtjs Custom Elements Renderer_ which does not exist.

https://github.com/drunomics/lupus-decoupled-website/blob/main/content/3.advanced-topics/60.drupal-forms.md?plain=1#L5

I suppose it is meant Lupus CE renderer (https://www.drupal.org/project/lupus_ce_renderer) or is it Nuxt Custom elements connector (https://github.com/drunomics/nuxtjs-drupal-ce/tree/2.x)?

**Comment by fago** [comment]
right. not sure, that sentence is just not necessary and might be some copy/paste error. I just dropped it.
https://github.com/drunomics/lupus-decoupled-website/commit/0c7a734a935c4bee205cebde4e5b8bf1771bdd78
